# .travis.yml
 
language:
  php
 
sudo:
  required
 
services:
  docker 

before_install:
  - docker -v

install:
  - docker-compose up -d

script:
  # Run your tests here.
  - echo 'Tested'
  - docker ps

after_success:
  - echo 'Got to the end!'