# .travis.yml
 
language:
  php
 
sudo:
  required
 
services:
  docker 

before_install:
  - './.travis/update.sh'
  - sudo /etc/init.d/mysql stop

script:
  # Run your tests here.
  - echo 'Tested'
  - docker ps
  - docker build -t $IMAGE .

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push $IMAGE ;
    fi
  - echo 'Got to the end!'