# .travis.yml
 
language:
  php
 
sudo:
  required
 
services:
  docker 

before_install:
  - docker --version

install:
  - docker-compose --version
  - docker-compose up -d

before_script:
  - sudo /etc/init.d/mysql stop
  
script:
  # Run your tests here.
  - echo 'Tested'
  - docker ps

after_success:
  - echo 'Got to the end!'