# .travis.yml
 
language:
  php
 
sudo:
  required

dist:
  trusty
 
services:
  docker 

before_install:
  - docker --version
  - docker-compose --version
  - sudo /etc/init.d/mysql stop

jobs:
  include:
    - stage: launch docker
      script:
        - docker-compose up -d
        - docker ps
    - stage: build docker image
      script:
        - echo 'Building image'
        - docker build -t staging-build .
        - docker images
    - stage: test docker image
      script:
        - echo 'test scripts here'

after_success:
  - echo 'Got to the end!'