version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db/db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - back

  wp:
    depends_on:
      - db
    # image: thirstypanda/staging-build
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wp-content:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    working_dir: /var/www/html
    networks:
      - back

  codecept:
    image: codeception/codeception
    depends_on:
      - chrome
      - wp
    volumes:
      - './tests:/project/tests'
      - './codeception.yml:/project/codeception.yml'
    networks:
      - back

  chrome:
    image: selenium/standalone-chrome
    ports:
      - '4444:4444'
    environment:
      - no_proxy=localhost
    networks:
      - back


networks:
  back:
volumes:
  db_data:
